# Generated by Django 4.1.7 on 2023-03-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('count_pizza', models.IntegerField()),
                ('count_drink', models.IntegerField()),
                ('price', models.IntegerField()),
                ('user_id', models.CharField(max_length=6, null=True)),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('user_id', models.CharField(max_length=6)),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.sale')),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
    ]
