# Generated by Django 4.1.7 on 2023-03-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='user_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
