# Generated by Django 4.1.7 on 2023-02-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_detail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.sale'),
        ),
    ]
