# Generated by Django 4.1.7 on 2023-02-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_detail_sale_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'get_latest_by': 'date'},
        ),
    ]
